apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-index
  namespace: apps
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>SRE GitOps Lab</title>
      </head>
      <body>
        <h1>âœ… Caddy is running (GitOps)</h1>
        <p>If you can read this, Kubernetes + Flux are working.</p>
      </body>
    </html>
