apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository-grafana.yaml
  - loki-helmrelease.yaml
  - promtail-helmrelease.yaml
  - grafana-loki-datasource.yaml
